insert into books (id, `title`) values (1, 'Война и Мир');
insert into books (id, `title`) values (2, 'Воскресение');
insert into books (id, `title`) values (3, 'Евгений Онегин');
insert into books (id, `title`) values (4, 'Ночной дозор');
insert into authors (id, `name`) values (1, 'Лев Николаевич Толстой');
insert into authors (id, `name`) values (2, 'Александр Сергеевич Пушкин');
insert into authors (id, `name`) values (3, 'Сергей Васильевич Лукьяненко');
insert into genres (id, `title`) values (1, 'Война');
insert into genres (id, `title`) values (2, 'Мир');
insert into genres (id, `title`) values (3, 'Роман в стихах');
insert into genres (id, `title`) values (4, 'Городское фентези');
insert into genres (id, `title`) values (5, 'Драмма');
insert into book_author (`book_id`, `author_id`) values (1, 1);
insert into book_genre (`book_id`, `genre_id`) values (1, 1);
insert into book_genre (`book_id`, `genre_id`) values (1, 2);
insert into book_author (`book_id`, `author_id`) values (2, 1);
insert into book_genre (`book_id`, `genre_id`) values (2, 5);
insert into book_author (`book_id`, `author_id`) values (3, 2);
insert into book_genre (`book_id`, `genre_id`) values (3, 3);
insert into book_author (`book_id`, `author_id`) values (4, 3);
insert into book_genre (`book_id`, `genre_id`) values (4, 4);