spring:
  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: admin
    password:
    data: "data.sql" 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
 spring:
  profiles: "dev"       
---
spring:  profiles: "test"  datasource:    data: "test-data.sql"