spring:
  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: admin
    password:
    data: "data.sql" 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
        
---
spring:  profiles: "test"  datasource:    data: "test-data.sql"