version: '3'
services:
  journal:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - MONGO_URL=mongodb://mongo:27017/journal
      - MONGO_PORT=27017
    ports:
      - "8080:8080"
    networks:
      - nw
  mongo:
    image: "mongo"
    volumes:
      - /D/MongoDB/db:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      - nw
networks:
  nw:
